# AULA 11: MERGE

In [2]:
import pandas as pd

In [3]:
vendasDF = pd.read_excel("Vendas_Merge.xlsx")
display(vendasDF)

,Id Vendedor,ID Produto,Data Venda,Quantidade Vendida,Valor Unitário,Total Vendas
0,27264,100482,2023-01-01,8,89.99,719.92
1,21732,100359,2023-01-02,2,69.99,139.98
2,27082,100105,2023-01-03,2,153.40,306.80
3,22936,100212,2023-01-04,10,148.56,1485.60
4,21164,100244,2023-01-05,6,146.14,876.84
5,28824,100301,2023-01-06,2,224.14,448.28
6,27264,100345,2023-01-07,4,150.50,602.00
7,21732,100411,2023-01-08,4,248.73,994.92
8,27082,100128,2023-01-09,9,116.52,1048.68
9,22936,100877,2023-01-10,1,59.90,59.90
10,27264,100208,2023-01-11,6,46.90,281.40
11,21732,100226,2023-01-12,2,41.90,83.80
12,27082,100128,2023-01-13,7,81.90,573.30
13,22936,100443,2023-01-14,9,55.90,503.10
14,21732,100001,2023-01-15,8,89.90,719.20
15,37579,100482,2023-01-16,4,89.99,359.96
16,20437,100359,2023-01-17,7,69.99,489.93
17,21732,100105,2023-01-18,7,153.40,1073.80
18,27082,100212,2023-01-19,7,148.56,1039.92
19,27264,100244,2023-01-20,9,146.14,1315.26
20,28824,100301,2023-01-21,6,224.14,1344.84
21,27264,100345,2023-01-22,6,150.50,903.00
22,21732,100411,2023-01-23,4,248.73,994.92
23,27082,100128,2023-01-24,9,116.52,1048.68
24,22936,100877,2023-01-25,8,59.90,479.20
25,21732,100208,2023-01-26,5,46.90,234.50
26,27082,100226,2023-01-27,9,41.90,377.10
27,22936,100128,2023-01-28,9,81.90,737.10

In [10]:
vendedoresDF = pd.read_excel("Vendedores_Merge.xlsx")
produtosDF = pd.read_excel("Produtos_Merge.xlsx")

#Método Merge -> trás informações de outros DF para um outro DF através de um 
#identificador. Ou seja, junta informações de um arquivo em outro

vendasDF = vendasDF.merge(vendedoresDF)

vendasDF = vendasDF.merge(produtosDF)
display(vendasDF)

print(vendasDF.columns)

,Id Vendedor,ID Produto,Data Venda,Quantidade Vendida,Valor Unitário,Total Vendas,Vendedor,Meta,Produto
0,27264,100482,2023-01-01,8,89.99,719.92,Leonardo Almeida,5000,Tênis Feminino
1,37579,100482,2023-01-16,4,89.99,359.96,Angela Maria,5000,Tênis Feminino
2,27264,100345,2023-01-07,4,150.50,602.00,Leonardo Almeida,5000,Jaqueta Masculina Preta
3,27264,100345,2023-01-22,6,150.50,903.00,Leonardo Almeida,5000,Jaqueta Masculina Preta
4,27264,100208,2023-01-11,6,46.90,281.40,Leonardo Almeida,5000,Calça Bailarina
5,21732,100208,2023-01-26,5,46.90,234.50,Eliane Moreira,5000,Calça Bailarina
6,27264,100244,2023-01-20,9,146.14,1315.26,Leonardo Almeida,5000,Camisa Masculina Festa Balada
7,21164,100244,2023-01-05,6,146.14,876.84,Paulo Santos,5000,Camisa Masculina Festa Balada
8,21732,100359,2023-01-02,2,69.99,139.98,Eliane Moreira,5000,Calça Feminina Jogger
9,20437,100359,2023-01-17,7,69.99,489.93,Carlos Moreira,5000,Calça Feminina Jogger
10,21732,100411,2023-01-08,4,248.73,994.92,Eliane Moreira,5000,Bolsa de Trabalho
11,21732,100411,2023-01-23,4,248.73,994.92,Eliane Moreira,5000,Bolsa de Trabalho
12,21732,100226,2023-01-12,2,41.90,83.80,Eliane Moreira,5000,Camisa Térmica
13,27082,100226,2023-01-27,9,41.90,377.10,Nicolas Pereira,5000,Camisa Térmica
14,21732,100001,2023-01-15,8,89.90,719.20,Eliane Moreira,5000,Colar Pingente
15,21732,100105,2023-01-18,7,153.40,1073.80,Eliane Moreira,5000,Camisa Masculina
16,27082,100105,2023-01-03,2,153.40,306.80,Nicolas Pereira,5000,Camisa Masculina
17,27082,100128,2023-01-09,9,116.52,1048.68,Nicolas Pereira,5000,Kit de Pinceis de Maquiagem
18,27082,100128,2023-01-24,9,116.52,1048.68,Nicolas Pereira,5000,Kit de Pinceis de Maquiagem
19,27082,100128,2023-01-13,7,81.90,573.30,Nicolas Pereira,5000,Sapato Social
20,22936,100128,2023-01-28,9,81.90,737.10,Amanda Martins,5000,Sapato Social
21,27082,100212,2023-01-19,7,148.56,1039.92,Nicolas Pereira,5000,Bermuda Masculino
22,22936,100212,2023-01-04,10,148.56,1485.60,Amanda Martins,5000,Bermuda Masculino
23,22936,100877,2023-01-10,1,59.90,59.90,Amanda Martins,5000,Vestido Infantil
24,22936,100877,2023-01-25,8,59.90,479.20,Amanda Martins,5000,Vestido Infantil
25,22936,100443,2023-01-14,9,55.90,503.10,Amanda Martins,5000,Sapatilha Sapato
26,28824,100301,2023-01-06,2,224.14,448.28,Gabriel Cardoso,5000,Bota Masculina
27,28824,100301,2023-01-21,6,224.14,1344.84,Gabriel Cardoso,5000,Bota Masculina

Index(['Id Vendedor', 'ID Produto', 'Data Venda', 'Quantidade Vendida',
       'Valor Unitário', 'Total Vendas', 'Vendedor', 'Meta', 'Produto'],
      dtype='object')

In [11]:
resumoDataFrame = vendasDF[["Vendedor","Produto","Total Vendas"]]
display(resumoDataFrame)

            Vendedor                        Produto  Total Vendas
0   Leonardo Almeida                 Tênis Feminino        719.92
1       Angela Maria                 Tênis Feminino        359.96
2   Leonardo Almeida        Jaqueta Masculina Preta        602.00
3   Leonardo Almeida        Jaqueta Masculina Preta        903.00
4   Leonardo Almeida                Calça Bailarina        281.40
5     Eliane Moreira                Calça Bailarina        234.50
6   Leonardo Almeida  Camisa Masculina Festa Balada       1315.26
7       Paulo Santos  Camisa Masculina Festa Balada        876.84
8     Eliane Moreira          Calça Feminina Jogger        139.98
9     Carlos Moreira          Calça Feminina Jogger        489.93
10    Eliane Moreira              Bolsa de Trabalho        994.92
11    Eliane Moreira              Bolsa de Trabalho        994.92
12    Eliane Moreira                 Camisa Térmica         83.80
13   Nicolas Pereira                 Camisa Térmica        377.10
14    Eliane Moreira                 Colar Pingente        719.20
15    Eliane Moreira               Camisa Masculina       1073.80
16   Nicolas Pereira               Camisa Masculina        306.80
17   Nicolas Pereira    Kit de Pinceis de Maquiagem       1048.68
18   Nicolas Pereira    Kit de Pinceis de Maquiagem       1048.68
19   Nicolas Pereira                  Sapato Social        573.30
20    Amanda Martins                  Sapato Social        737.10
21   Nicolas Pereira              Bermuda Masculino       1039.92
22    Amanda Martins              Bermuda Masculino       1485.60
23    Amanda Martins               Vestido Infantil         59.90
24    Amanda Martins               Vestido Infantil        479.20
25    Amanda Martins               Sapatilha Sapato        503.10
26   Gabriel Cardoso                 Bota Masculina        448.28
27   Gabriel Cardoso                 Bota Masculina       1344.84